"""added news tags support

Revision ID: 1856a5ff3459
Revises: 8c1c486010a1
Create Date: 2026-01-02 20:29:07.555243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1856a5ff3459'
down_revision: Union[str, None] = '8c1c486010a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_news',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'tag_id')
    )
    op.drop_column('news', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('tag_news')
    # ### end Alembic commands ###
