"""Added field image_url for Dog

Revision ID: 355758ef62b1
Revises: a9dc7e7b0969
Create Date: 2025-12-25 20:27:28.800057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355758ef62b1'
down_revision: Union[str, None] = 'a9dc7e7b0969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'image_url')
    # ### end Alembic commands ###
