"""Add foreign keys to adoption/guardian requests

Revision ID: 695b1916bdb6
Revises: dd44a6b76a02
Create Date: 2026-01-02 22:12:08.258748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695b1916bdb6'
down_revision: Union[str, None] = 'dd44a6b76a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'adoption_request', 'request', ['request_id'], ['id'])
    op.create_foreign_key(None, 'guardian_request', 'request', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guardian_request', type_='foreignkey')
    op.drop_constraint(None, 'adoption_request', type_='foreignkey')
    # ### end Alembic commands ###
