"""Replaced field name in News from news_image_id to image_url

Revision ID: 8c1c486010a1
Revises: 355758ef62b1
Create Date: 2025-12-29 15:52:19.633355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1c486010a1'
down_revision: Union[str, None] = '355758ef62b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_column('news', 'news_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('news_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('news', 'image_url')
    # ### end Alembic commands ###
