"""Added Tags, tags_dogs. Modified Dogs

Revision ID: a9dc7e7b0969
Revises: a9963c9d739d
Create Date: 2025-12-18 23:30:07.610127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a9dc7e7b0969'
down_revision: Union[str, None] = 'a9963c9d739d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    gender_enum = postgresql.ENUM('MALE', 'FEMALE', name='genderenum')
    gender_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_dog',
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dog_id', 'tag_id')
    )
    op.add_column('dog', sa.Column('breed', sa.String(length=100), nullable=False))
    op.add_column('dog', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('dog', sa.Column('intake_date', sa.Date(), nullable=True))
    op.add_column('dog', sa.Column('veterinary_passport', sa.Boolean(), nullable=False))
    op.add_column('dog', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'gender')
    op.drop_column('dog', 'veterinary_passport')
    op.drop_column('dog', 'intake_date')
    op.drop_column('dog', 'description')
    op.drop_column('dog', 'breed')
    op.drop_table('tag_dog')
    op.drop_table('tag')
    gender_enum = postgresql.ENUM('MALE', 'FEMALE', name='genderenum')
    gender_enum.drop(op.get_bind())
    # ### end Alembic commands ###
