"""Added RequestModel, AdoptionRequestModel, GuardianRequestModel

Revision ID: dd44a6b76a02
Revises: 355758ef62b1
Create Date: 2026-01-02 17:59:07.908414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd44a6b76a02'
down_revision: Union[str, None] = '355758ef62b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('family_member_count', sa.Enum('ONE', 'WITH_CHILDREN', 'COUPLE', name='familymembercountenum'), nullable=False),
    sa.Column('had_experience_adoption_pet', sa.Enum('FIRST_PET', 'HAD_PETS_BEFORE', 'CURRENTLY_HAVE_PETS', name='petexperienceenum'), nullable=False),
    sa.Column('adoption_purpose', sa.Enum('FOR_SELF', 'AS_GIFT', name='adoptionpurposeenum'), nullable=False),
    sa.Column('housing_type', sa.Enum('RENTED', 'APARTMENT', 'HOUSE', name='housingtypeenum'), nullable=False),
    sa.Column('housing_area', sa.Enum('UP_TO_40', 'BETWEEN_40_60', 'OVER_60', name='housingareaenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('guardian_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('ADOPTION_REQUEST', 'GUARDIAN_REQUEST', name='requesttypeenum'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', name='requeststatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('guardian_request')
    op.drop_table('adoption_request')
    # ### end Alembic commands ###
